apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: search
          image: iamrobins/mapinsight_server-search
          envFrom:
            - configMapRef:
                name: search-configmap
            - secretRef:
                name: search-secret